.PHONY: clean All

All:
	@echo "----------Building project:[ consumer - Debug ]----------"
	@cd "consumer" && $(MAKE) -f  "consumer.mk"
clean:
	@echo "----------Cleaning project:[ consumer - Debug ]----------"
	@cd "consumer" && $(MAKE) -f  "consumer.mk" clean
