.PHONY: clean All

All:
	@echo "----------Building project:[ shared_mem_writer - Debug ]----------"
	@cd "shared_mem_writer" && $(MAKE) -f  "shared_mem_writer.mk"
clean:
	@echo "----------Cleaning project:[ shared_mem_writer - Debug ]----------"
	@cd "shared_mem_writer" && $(MAKE) -f  "shared_mem_writer.mk" clean
