.PHONY: clean All

All:
	@echo "----------Building project:[ Controller - Debug ]----------"
	@cd "Controller" && $(MAKE) -f  "Controller.mk"
clean:
	@echo "----------Cleaning project:[ Controller - Debug ]----------"
	@cd "Controller" && $(MAKE) -f  "Controller.mk" clean
