.PHONY: clean All

All:
	@echo "----------Building project:[ consumer - Debug ]----------"
	@cd "/home/aron/Desktop/Test_area/FiFo/fifo/consumer" && $(MAKE) -f  "consumer.mk"
clean:
	@echo "----------Cleaning project:[ consumer - Debug ]----------"
	@cd "/home/aron/Desktop/Test_area/FiFo/fifo/consumer" && $(MAKE) -f  "consumer.mk" clean
