.PHONY: clean All

All:
	@echo "----------Building project:[ shared_mem_read - Debug ]----------"
	@cd "/home/pi/Desktop/Test_area/Testrig/FiFo/fifo/shared_mem_read" && "$(MAKE)" -f  "shared_mem_read.mk"
clean:
	@echo "----------Cleaning project:[ shared_mem_read - Debug ]----------"
	@cd "/home/pi/Desktop/Test_area/Testrig/FiFo/fifo/shared_mem_read" && "$(MAKE)" -f  "shared_mem_read.mk" clean
